import tensorflow as tf

from utils.utils import convert_params, convert_variables_without_trainable


approximate_options1 = [
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.Adam(learning_rate=0.5),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.Adam(learning_rate=0.7),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.Adam(learning_rate=0.9),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=0.5),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=0.7),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=0.9),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=1),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=0.5, momentum=0.5),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=0.7, momentum=0.5),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=0.9, momentum=0.5),
        "eps": 0.0001,
        "max_steps": 1000,
    },
    {
        "x": [convert_variables_without_trainable([x, x]) for x in range(-10, 10, 1)],
        "x_validate": [convert_variables_without_trainable([x, x]) for x in range(-11, 10, 1)],
        "params": convert_params([[1.0 for x in range(2)] for y in range(2)]),
        "loss_function": tf.keras.losses.MAE,
        "opt": tf.keras.optimizers.SGD(learning_rate=1.1, momentum=0.5),
        "eps": 0.0001,
        "max_steps": 1000,
    },


]
